/**
 * Reads .env and generates src/environments/environment*.ts
 * Run automatically before start/build via package.json scripts.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const envPath = path.join(root, '.env');

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    console.error(`Missing ${filePath}. Copy .env.example to .env and fill in Firebase values.`);
    process.exit(1);
  }

  const vars = {};
  const lines = fs.readFileSync(filePath, 'utf8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    vars[key] = value;
  }
  return vars;
}

function requireKeys(vars, keys) {
  const missing = keys.filter((k) => !vars[k]);
  if (missing.length) {
    console.error(`Missing required .env keys: ${missing.join(', ')}`);
    process.exit(1);
  }
}

const keys = [
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_DATABASE_URL',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
  'FIREBASE_MEASUREMENT_ID',
];

const vars = parseEnvFile(envPath);
requireKeys(vars, keys);

function buildFile(production) {
  return `// Auto-generated by scripts/generate-env.js — do not edit manually.
// Source: .env (run \`npm run env\` to regenerate)

export const environment = {
  production: ${production},
  firebase: {
    apiKey: '${vars.FIREBASE_API_KEY}',
    authDomain: '${vars.FIREBASE_AUTH_DOMAIN}',
    databaseURL: '${vars.FIREBASE_DATABASE_URL}',
    projectId: '${vars.FIREBASE_PROJECT_ID}',
    storageBucket: '${vars.FIREBASE_STORAGE_BUCKET}',
    messagingSenderId: '${vars.FIREBASE_MESSAGING_SENDER_ID}',
    appId: '${vars.FIREBASE_APP_ID}',
    measurementId: '${vars.FIREBASE_MEASUREMENT_ID}'
  }
};
`;
}

const envDir = path.join(root, 'src', 'environments');
fs.writeFileSync(path.join(envDir, 'environment.ts'), buildFile(false));
fs.writeFileSync(path.join(envDir, 'environment.prod.ts'), buildFile(true));
console.log('Generated environment.ts and environment.prod.ts from .env');
